export enum cSort {
	PopularityDesc = 'POPULARITY_DESC',
	Popularity = 'POPULARITY',
	TrendingDesc = 'TRENDING_DESC',
	Trending = 'TRENDING',
	UpdatedAtDesc = 'UPDATED_AT_DESC',
	UpdatedAt = 'UPDATED_AT',
	StartDateDesc = 'START_DATE_DESC',
	StartDate = 'START_DATE',
	EndDateDesc = 'END_DATE_DESC',
	EndDate = 'END_DATE',
	FavouritesDesc = 'FAVOURITES_DESC',
	Favourites = 'FAVOURITES',
	ScoreDec = 'SCORE_DESC',
	Score = 'SCORE',
	TitleRomajiDesc = 'TITLE_ROMAJI_DESC',
	TitleRomaji = 'TITLE_ROMAJI',
	TitleEnglishDesc = 'TITLE_ENGLISH_DESC',
	TitleEnglish = 'TITLE_ENGLISH',
	TitleNativeDesc = 'TITLE_NATIVE_DESC',
	TitleNative = 'TITLE_NATIVE',
	EpisodeDesc = 'EPISODES_DESC',
	Episode = 'EPISODES',
	ID = 'ID',
	IDDesc = 'ID_DESC'
}
